### ISSUE TITLE
Can't compile with Stylus

### ISSUE THREAD

**Issue by KolesnichenkoDS** [jenius/rupture#55]
Stylus can't compile `0.6.1` version, so I have to use `0.6.0` version

![](https://pp.vk.me/c623117/v623117626/20a97/jL_FpBrrvfQ.jpg)

**Comment by jenius** [comment]
@declandewet it seems like this is the issue here:

https://github.com/jenius/rupture/commit/426054d3f186aa84907671af2aa9a8acd4876ed0#diff-5f8ee28a7c08e245155174aaebb8532fR93

Could you take a look at this?

**Comment by jenius** [comment]
Thanks for reporting @KolesnichenkoDS we'll get this worked out shortly

**Comment by declandewet** [comment]
I can't seem to reproduce this. @KolesnichenkoDS, what OS, version of Stylus, and build system are you using to compile this?

**Comment by KolesnichenkoDS** [comment]
@declandewet, **GruntJS** with **grunt-contrib-stylus 0.11.0** on **Debian Jessie** and **Windows 7**

**Comment by Panya** [comment]
@KolesnichenkoDS  grunt-contrib-stylus 0.11.0 uses very old version of Stylus (0.41.0 was released more than 2 years ago).The version doesn't support many of features that needed in Rupture. Try to update grunt-contrib-stylus to the latest version.

**Comment by jenius** [comment]
Thanks for helping out here guys. Based on that info, I'm going to go ahead and close this issue out :grinning:
