### ISSUE TITLE
How to use `+from-width` in conjunction with `@media print`?

### ISSUE THREAD

**Issue by rotorz** [jenius/rupture#57]
Hey all!

Let's suppose that I would like a set of styles to be included if either a) `+from-width(720px)` or b) `@media print` is true:
```stylus
@media print, +from-width(720px)
    .special-thingy
        color blue
```
Unless I am missing something, this does not appear to be working.

Is there an easy way to achieve this with rupture to avoid resorting to something like the following each time?
```stylus
special-thingy-helper()
    .special-thingy
        color blue

@media print
    special-thingy-helper()
+from-width(720px)
    special-thingy-helper()
```
Cheers!

**Comment by declandewet** [comment]
As far as I know, Rupture does not support grouping of media queries like that, and likely never will because of how block mixins in Stylus work. This works for your intended use case.

```
.special-thingy
  @media print
    color: blue
  +from-width(720px)
    color: blue
```

**Comment by rotorz** [comment]
Thanks for the super fast response!

I feared that this might be the case; I'll probably stick to using the mixin workaround to avoid repetition in the Stylus files.

Cheers :)

**Comment by jenius** [comment]
Sorry about that! You could try opening an issue in stylus if you want to press it :grinning:
