### ISSUE TITLE
Rupture isn't working on my iPhone.

### ISSUE THREAD

**Issue by Splendorr** [jenius/rupture#60]
Rupture appears to be functioning properly on my desktop. But when I load the site in iOS Safari or Chrome, there's no way to make it react properly. Rather, it keeps showing the content that should be for the largest screen size, which is also the last code in the line, if that matters.

I'm using a Roots setup, with the app.coffee files including:
````
stylus:
    use: [axis(), rupture(), jeet(), autoprefixer()]
````

I'm not doing:
````
@import 'rupture'
````
in my stylesheet, but adding that doesn't seem to make a difference.

No matter how high I set the threshold, nothing changes.

Here's the Stylus:
````
.video
      stack()
      col(1)
      transition: all .5s ease
      
      +above(800px)
        unstack();
        col(1/4)
````

Here's the generated CSS:
````
#container .video {
  display: block;
  clear: both;
  float: none;
  width: 100%;
  margin-left: auto;
  margin-right: auto;
  *zoom: 1;
  float: left;
  clear: none;
  text-align: inherit;
  width: 100%;
  margin-left: 0%;
  margin-right: 3%;
  transition: all 0.5s ease;
}
#container .video:first-child {
  margin-left: auto;
}
#container .video:last-child {
  margin-right: auto;
}
#container .video:before,
#container .video:after {
  content: '';
  display: table;
}
#container .video:after {
  clear: both;
}
#container .video:last-child {
  margin-right: 0%;
}
@media only screen and (min-width: 800px) {
  #container .video {
    text-align: left;
    display: inline;
    clear: none;
    width: auto;
    margin-left: 0;
    margin-right: 0;
    *zoom: 1;
    float: left;
    clear: none;
    text-align: inherit;
    width: 22.75%;
    margin-left: 0%;
    margin-right: 3%;
  }
  #container .video:first-child {
    margin-left: 0;
  }
  #container .video:last-child {
    margin-right: 0;
  }
  #container .video:before,
  #container .video:after {
    content: '';
    display: table;
  }
  #container .video:after {
    clear: both;
  }
  #container .video:last-child {
    margin-right: 0%;
  }
}
````

**Comment by Splendorr** [comment]
Here's the widescreen desktop, which is also what it looks like on iPhone portrait:
![screen shot 2015-05-03 at 6 58 55 pm](https://cloud.githubusercontent.com/assets/150489/7447366/83fd3316-f1c6-11e4-9858-9079bfddabca.PNG)

And then showing that narrowing the window collapses the col()s:
![screen shot 2015-05-03 at 6 59 01 pm](https://cloud.githubusercontent.com/assets/150489/7447368/99db6fcc-f1c6-11e4-8046-d4eec7ab4dcd.PNG)

**Comment by DavidOliver** [comment]
What is your viewport meta tag set to?

**Comment by Splendorr** [comment]
_Holy smokes_ that was it, @DavidOliver ! Duhhhh! Haha. This is my first project in a while using a new starting point, and that basic line just fell off my radar. Hoooo yeah! I knew it had to be something silly like that. Thanks so much, and sorry to waste your time!

**Comment by Splendorr** [comment]
So, just to clarify, as soon as I added the line
````
meta(name="viewport" content="width=device-width, initial-scale=1")
````
to the header content of my page, everything behaved as expected.

**Comment by DavidOliver** [comment]
Heh. Easily done, eh?
