### ISSUE TITLE
1px problem

### ISSUE THREAD

**Issue by theobroma** [jenius/rupture#61]
I am trying to apply styles using +desktop() and it generates min-width: 992px (my desktop-cutoff:992px).
Also I apply other incompatible styles on the above  using +below(2) and it generates max-width: 992px.
On 992px styles meet each other! The same happening when I use +above(3) instead of +desktop().
What is the best way to prevent it?

**Comment by declandewet** [comment]
Hi @theobrama, what you're looking for is a feature called [anti-overlap](https://github.com/jenius/rupture#scale-overlap). So, given the documentation, you have two options:

1. Set the anti-overlap globally
```stylus
rupture.anti-overlap = 1px
// OR
rupture.anti-overlap = true
```

OR

2. setting the anti-overlap at the mixin level

```stylus
.some-selector
  +below(2, anti-overlap: 1px)
    // some styles
```

**Comment by jenius** [comment]
Thanks @declandewet!
