### ISSUE TITLE
Nothing happening when emulated device is right on a breakpoint/slice

### ISSUE THREAD

**Issue by robgillan** [jenius/rupture#64]
This is my first time filing an issue, so first and foremost I hope this actually something that may need adjusting and isn't just a problem with how I'm using it.

I have a regular nav bar and a mobile nav bar that are in two separate `div`s. I've set one or the other to hide depending on device by using the following Rupture breakpoints:

    .navigation
      +below(4)
        display: none
        ...

    .mobile-nav
      +above(4)
        display: none
        ...

The issue is that when emulating devices in Chrome, the Nexus 10 tablet (which is configured to be: `800x1280`) shows neither. If I change the device width manually to `799` then the mobile-nav hamburger appears. However, changing it to be `801` doesn't render the regular nav. Any insight?

**Comment by DavidOliver** [comment]
It might be solvable with [the anti-overlap setting](https://github.com/jenius/rupture#scale-overlap).

However, I recommend slightly changing your approach so that it's "mobile first", which should avoid the issue altogether.

    .navigation
      display: none
      +above(4)
        display: block

    .mobile-nav
      +above(4)
        display: none

**Comment by robgillan** [comment]
Thanks David, I'll give this a shot. It still seems curious to me that a device (even if emulated) that falls right on a breakpoint would slip through the cracks. I suppose my approach though is kind of like saying:

`if (x > 0 || x < 0)` where 0 itself is not ever considered. 

I guess that's the crux of my issue, though - does Rupture treat these as greater than but not equal to?
