### ISSUE TITLE
Is there a way to state +above(tablet)?

### ISSUE THREAD

**Issue by permadesign** [jenius/rupture#69]
I often end up duplicating rules for +tablet() and +desktop(), as +tablet is between it's lower and higher limits rather than above it's lower limit. What would be the best way around this? I love the functionality otherwise.

**Comment by declandewet** [comment]
@permadesign Not sure I understood correctly, but the lowest cutoff for tablet is `mobile`, so you could do this:

```stylus
+above(rupture.mobile-cutoff)
// OR
+above('s')
```

Which basically means "apply these styles if the viewport is above the largest mobile breakpoint/smallest tablet breakpoint"

**Comment by permadesign** [comment]
That's perfect, thanks!
